name: "Prepare env"
description: "Prepare rust environment"
inputs:
  token:
    description: "Token for setup-protoc"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install LLVM and Clang
      if: runner.os == 'Linux'
      id: llvm_setup
      shell: bash
      run: |
        LLVM_VERSION=$(rustc --verbose --version | grep -Po 'LLVM version: \K\d+\.\d+.\d+')
        LLVM_MAJOR_VERSION=$(rustc --verbose --version | grep -Po 'LLVM version: \K\d+')
        UBUNTU_VERSION=$(lsb_release -a | grep -Po 'Codename:\t\K\w+')
        echo "LLVM_VERSION=$LLVM_VERSION" >> $GITHUB_OUTPUT
        echo "LLVM_MAJOR_VERSION=$LLVM_MAJOR_VERSION" >> $GITHUB_OUTPUT
        echo "UBUNTU_VERSION=$UBUNTU_VERSION" >> $GITHUB_OUTPUT
    - name: Install LLVM and Clang
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/${{ steps.llvm_setup.outputs.UBUNTU_VERSION }}/ llvm-toolchain-${{ steps.llvm_setup.outputs.UBUNTU_VERSION }}-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} main"
        sudo apt-get update
        sudo apt-get install --yes autoconf libtool libsecp256k1-dev libsodium-dev liblz4-dev clang-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} lldb-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} lld-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} libc++-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }}-dev libc++abi-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }}-dev libunwind-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }}-dev
    - shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/lld-link lld-link /usr/bin/lld-link-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101
        sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-${{ steps.llvm_setup.outputs.LLVM_MAJOR_VERSION }} 101

    - run: brew install secp256k1 libsodium lz4 autoconf automake libtool zlib
      shell: bash
      if: runner.os == 'macOS'
